name: GitHub Classroom Workflow

on: push

permissions:
  checks: write
  issues: write
  actions: read
  contents: read

jobs:
  grading:
      run: sudo apt-get install python3-tk
      if: ${{ !contains(github.actor, 'classroom') }}
      uses: BZZ-Commons/workflows/.github/workflows/grading.yml@main
      with:
        MOODLE: true  # CHANGE true=export grade to moodle
      secrets: inherit
